Clearml extract corpora is working now on S3.  Need to test out the …
sillsdev/silnlp pull request #21
Opened 2021-05-14 20:02 UTC by johnml1135

…other functions (preprocess, train and test).

2021-05-14 20:06 UTC, johnml1135 commented
We can merge now to try out - I have not tested other functions.  They will need to have clearml code added to them as well.  This could be done by anybody though and the lifting of getting S3 working is done.  I have S3 mounted on my PC, but we also need to work and get it mounted on the other drives as well.

There is a significant possibility that S3 will not like being treated as a folder structure (appends, other trickery) and may crash and need to be restarted.  If this becomes a bigger issue, we may need to investigate other solutions.

I documented my work trying to resolve this issue here: https://stackoverflow.com/questions/67496760/mounting-an-s3-bucket-in-docker-in-a-clearml-agent/67497264#67497264

2021-05-14 20:07 UTC, johnml1135 commented
This is a fix for #7 issue.

2021-05-18 06:52 UTC, ddaspit requested changes

2021-05-18 06:52 UTC, ddaspit commented on scripts/clearml_agent/mount_aqua_on_data.bat
> +call wsl.exe fusermount -uz /data/aqua-ml-data
What about Linux? Also, maybe this path should be specified by the `SIL_NLP_DATA_PATH` environment variable.

2021-05-18 06:52 UTC, ddaspit commented on silnlp/common/environment.py
> +    auqa_ml_path = Path("/data/aqua-ml-data")
rclone should be mounted to the path specified by `SIL_NLP_DATA_PATH`, then this code won't be necessary.

2021-05-18 06:52 UTC, ddaspit commented on silnlp/common/extract_corpora.py
> +    task = Task.init(
I guess this is mostly done as a test ClearML task. I don't know how useful this would be in real-world use.

2021-05-18 10:36 UTC, johnml1135 commented
Have ClearML be an option in Extract Corpora
Make a nmt/experiment.py file - base experiment (no clearml) class for preprocess, train and test.  Child class with ClearML.

2021-05-18 10:37 UTC, johnml1135 commented
Run with 3 steps (create checkpoint there) - without GPU.

2021-05-25 19:42 UTC, johnml1135 commented
Damien, are you OK merging this in now?

2021-05-27 15:20 UTC, johnml1135 commented
Needs one more commit after clearml 1.0.3 comes out to update the lock file.

2021-05-28 20:48 UTC, merged

2021-05-31 05:09 UTC, ddaspit commented
I didn't get a chance to review this until today. The changes look good to me.

2021-05-31 05:10 UTC, ddaspit commented
Feel free to delete the branch if you don't need it anymore.