ignore OccursUnder in custom stylesheets when parsing book usfm
sillsdev/silnlp pull request #269
Opened 2023-12-12 21:19 UTC by mshannon-sil

This change adds the parameter `ignore_occurs_under` to `update_sheet()` in `style.py`, with the default set to `False`. When set to `True`, 'update_sheet()` ignores `OccursUnder` in custom stylesheets to prevent any parsing issues in `collect_segments_from_paragraph()`.  I set the option to `True` in every place where it is called when translating a book, and it is now handling the `\b` markers correctly in NIV84.

2023-12-12 22:33 UTC, ddaspit requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/269)* status: all files reviewed, 1 unresolved discussion (waiting on @mshannon-sil)

___
*[`silnlp/sfm/style.py` line 198 at r1](https://reviewable.io/reviews/sillsdev/silnlp/269#-NlV8Nte3Jk4hk5rWKRL:-NlV8Nte3Jk4hk5rWKRM:b-se1y6q) ([raw file](https://github.com/sillsdev/silnlp/blob/d7488fd0ed71e40d8f1114baaf87e1d1173d2dc0/silnlp/sfm/style.py#L198)):*
> ```Python
> 
> 
> def update_sheet(sheet, ammendments={}, field_replace=False, ignore_occurs_under=False, **kwds):
> ```

I would like to make this a bit more generic. We should update `field_replace` to accept an enum instead of a boolean. The enum will have three values: `REPLACE`, `MERGE`, and `IGNORE`.


<!-- Sent from Reviewable.io -->

2023-12-12 22:39 UTC, mshannon-sil commented
*[`silnlp/sfm/style.py` line 198 at r1](https://reviewable.io/reviews/sillsdev/silnlp/269#-NlV8Nte3Jk4hk5rWKRL:-NlVA3nO1tgB8XIJNsIU:b-q23enb) ([raw file](https://github.com/sillsdev/silnlp/blob/d7488fd0ed71e40d8f1114baaf87e1d1173d2dc0/silnlp/sfm/style.py#L198)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would like to make this a bit more generic. We should update `field_replace` to accept an enum instead of a boolean. The enum will have three values: `REPLACE`, `MERGE`, and `IGNORE`.
</blockquote></details>

So to clarify, would IGNORE ignore both OccursUnder and TextProperties then, since `field_replace` is tied to both?


<!-- Sent from Reviewable.io -->

2023-12-12 23:16 UTC, ddaspit reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/269)* status: all files reviewed, 1 unresolved discussion (waiting on @mshannon-sil)

___
*[`silnlp/sfm/style.py` line 198 at r1](https://reviewable.io/reviews/sillsdev/silnlp/269#-NlV8Nte3Jk4hk5rWKRL:-NlVJASg5U9SxUjh3rzd:byhscmn) ([raw file](https://github.com/sillsdev/silnlp/blob/d7488fd0ed71e40d8f1114baaf87e1d1173d2dc0/silnlp/sfm/style.py#L198)):*
<details><summary><i>Previously, mshannon-sil wrote…</i></summary><blockquote>

So to clarify, would IGNORE ignore both OccursUnder and TextProperties then, since `field_replace` is tied to both?
</blockquote></details>

Yes, that is correct. Both fields have a similar impact on the structure of the USFM.


<!-- Sent from Reviewable.io -->

2023-12-12 23:29 UTC, mshannon-sil commented
*[`silnlp/sfm/style.py` line 198 at r1](https://reviewable.io/reviews/sillsdev/silnlp/269#-NlV8Nte3Jk4hk5rWKRL:-NlVMAMyDLe3D1A--k2M:bkb5g98) ([raw file](https://github.com/sillsdev/silnlp/blob/d7488fd0ed71e40d8f1114baaf87e1d1173d2dc0/silnlp/sfm/style.py#L198)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Yes, that is correct. Both fields have a similar impact on the structure of the USFM.
</blockquote></details>

Okay, just pushed a commit with this change.


<!-- Sent from Reviewable.io -->

2023-12-12 23:32 UTC, mshannon-sil commented
*[`silnlp/sfm/style.py` line 198 at r1](https://reviewable.io/reviews/sillsdev/silnlp/269#-NlV8Nte3Jk4hk5rWKRL:-NlVMgJTBZMal9h7B-vV:b1buep1) ([raw file](https://github.com/sillsdev/silnlp/blob/d7488fd0ed71e40d8f1114baaf87e1d1173d2dc0/silnlp/sfm/style.py#L198)):*
<details><summary><i>Previously, mshannon-sil wrote…</i></summary><blockquote>

Okay, just pushed a commit with this change.
</blockquote></details>

After pushing, I realized maybe we should change the name of the variable as well, since it's not just True or False whether we want to replace something. How would something like `field_update` work?


<!-- Sent from Reviewable.io -->

2023-12-12 23:39 UTC, mshannon-sil commented
*[`silnlp/sfm/style.py` line 198 at r1](https://reviewable.io/reviews/sillsdev/silnlp/269#-NlV8Nte3Jk4hk5rWKRL:-NlVNZBS31q01RdwVco7:b-en0yfe) ([raw file](https://github.com/sillsdev/silnlp/blob/d7488fd0ed71e40d8f1114baaf87e1d1173d2dc0/silnlp/sfm/style.py#L198)):*
<details><summary><i>Previously, mshannon-sil wrote…</i></summary><blockquote>

After pushing, I realized maybe we should change the name of the variable as well, since it's not just True or False whether we want to replace something. How would something like `field_update` work?
</blockquote></details>

Also, I realize the docstring for `update_sheet` needs to be updated to reflect the changes as well. Unless we just want to remove it, since most of the other functions in SILNLP don't have docstrings.


<!-- Sent from Reviewable.io -->

2023-12-13 17:15 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/269#-:-NlZABun3htr6heoYFgB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mshannon-sil)



<!-- Sent from Reviewable.io -->

2023-12-14 05:29 UTC, merged