Make Deuterocanon optional in collect_verse_counts.py
sillsdev/silnlp pull request #376
Opened 2024-05-07 15:42 UTC by bhartmoore

Adds a `--deutero` flag to `collect_verse_counts.py` and omits counts for the Deuterocanon if it's not set. 

Warns user in console if the Deuterocanon exists in a project and is not included. Should not affect the onboarding tool, but Eli will verify.

2024-05-07 17:48 UTC, Enkidu93 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/376)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @bhartmoore and @ddaspit)

___
*[`silnlp/common/collect_verse_counts.py` line 151 at r1](https://reviewable.io/reviews/sillsdev/silnlp/376#-NxJ6hjU58IGRJaaH-FT:-NxJ6hjU58IGRJaaH-FU:b-5lct10) ([raw file](https://github.com/sillsdev/silnlp/blob/7e22a901860a199cbd1d25a5c31d8238cc74d623/silnlp/common/collect_verse_counts.py#L151)):*
> ```Python
>                     cur_book = vref.split(" ")[0]
>                     cur_chapter = int(vref.split(" ")[1].split(":")[0].strip())
>                     #if cur_book not in project_scope:
> ```

Is there a reason to leave this commented-out code in?
___
*[`silnlp/common/collect_verse_counts.py` line 194 at r1](https://reviewable.io/reviews/sillsdev/silnlp/376#-NxJ7FpgEYv-HuXHSO55:-NxJ7FpgEYv-HuXHSO56:b-vxxcs9) ([raw file](https://github.com/sillsdev/silnlp/blob/7e22a901860a199cbd1d25a5c31d8238cc74d623/silnlp/common/collect_verse_counts.py#L194)):*
> ```Python
>             verse_count_df.loc[f][ele] = counts[ele]
>             verse_percentage_df.loc[f][ele] = 100 * round(counts[ele] / sum(complete_book_counts[ele].values()), 3)
>             if ele not in project_scope:
> ```

In this case, I think you can simplify
```
for ... :
    if ... :
        #do stuff
        continue
    if ... :
        #do other stuff
```
like this:

```
for ... :
    if ... :
        #do stuff
    else ... :
        #do other stuff
```
    


<!-- Sent from Reviewable.io -->

2024-05-07 18:07 UTC, Enkidu93 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/376#-:-NxJEJg4CA3u7DCfSgi3:bg7igkv)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2024-05-07 18:12 UTC, bhartmoore commented
Thanks for the comments, Eli. 
- Removed commented code as an oversight.
- Changed continue... if to elif.

2024-05-08 05:30 UTC, davidbaines commented
Thanks for working on this Bethany. 
I tested this with a couple of command lines:
`python -m silnlp.common.collect_verse_counts --output-folder E:\Work\verse_counts_new_deutero --deutero --files en-NIV11R.txt;en-NIV11.txt;en-NIV84.txt`

and 
`python -m silnlp.common.collect_verse_counts --output-folder E:\Work\verse_counts_new --files en-NIV11R.txt;en-NIV11.txt;en-NIV84.txt `

 I noticed that the detailed percentages files are not being written. I've never used them and it doesn't look like the code you've changed should affect them.  It might be that the code that writes those is intended and under the `for filename, books in partially_complete_books.items():` 
 
The previous code ordered the files as `NIV11, NIV84, NIV11R`, the new code ordered them in reverse `NIV11R, NIV84, NIV11` when the `--deutero` option was applied and as `NIV11R, NIV11, NIV84` without that option. Perhaps we could sort them alphabetically?

2024-05-08 14:00 UTC, Enkidu93 reviewed
@davidbaines  It should only write a detailed percentage file if a book is partially complete (otherwise, the information would be redundant i.e. the book is complete or not even started, so drilling down to the chapter level wouldn't be useful), so for the NIV versions, there shouldn't be any such files.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/376#-:-NxNV4Vw3axbYuqfA2oM:b-i6h48o)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2024-05-08 14:39 UTC, davidbaines commented
> @davidbaines It should only write a detailed percentage file if a book is partially complete (otherwise, the information would be redundant i.e. the book is complete or not even started, so drilling down to the chapter level wouldn't be useful), so for the NIV versions, there shouldn't be any such files.
> 
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/376#-:-NxNV4Vw3axbYuqfA2oM:b-i6h48o)_ status: 0 of 1 files reviewed, all discussions resolved (waiting on @ddaspit)

Thanks Eli, That makes sense.

2024-05-08 14:45 UTC, bhartmoore commented
David, thank you for testing! 

I did find a tab level mistake on the `elif` (and subsequent) lines that was causing detailed percentages files not to be written for the `tpi*.txt` files in my tests. This is corrected. 

I looked into the file ordering a bit. Final ordering comes about in this line: 

`verse_count_df["file"] = [os.path.basename(extract_file_name) for extract_file_name in extract_files]`

Interestingly, it comes out a little differently each time in my tests (using `tpi*.txt` files), regardless of whether `--deutero` is set.

2024-06-28 21:17 UTC, isaac091 commented
I talked to Bethany and I'm going to close this PR because I'm doing a significant rewrite of `collect_verse_counts.py` and will include these changes.

2024-06-28 21:17 UTC, closed without merging