Issue 508 compare translations script
sillsdev/silnlp pull request #510
Opened 2024-09-10 16:02 UTC by TaperChipmunk32

- Created the compare_translations.py script and added it to silnlp/common
- The script takes 2 required arguments and 1 optional
     - dir-path - the path to the directory where the translations are found and where the comparison output will be stored
     - file-paths - the paths to each of the translation outputs that need to be compared, takes exactly 2 file paths
     - scorers - optional argument that contains the set of scorers to use for comparison, default is:
     {"bleu", "chrf3", "chrf3+", "chrf3++", "spbleu", "wer", "ter"}
- The output of this script is stored in comparison_scores.txt at dir-path and contains the relevant filenames and each scorer and result used.

I did not add an S3 bucket connection yet, but this script can be extended later on to add that functionality if needed.

2024-09-10 19:03 UTC, ddaspit requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/510)* status: all files reviewed, 1 unresolved discussion (waiting on @mshannon-sil and @TaperChipmunk32)

___
*[`silnlp/common/compare_translations.py` line 34 at r1](https://reviewable.io/reviews/sillsdev/silnlp/510#-O6SH-A_8gGKZ9can_34:-O6SH-A_8gGKZ9can_35:be4i9an) ([raw file](https://github.com/sillsdev/silnlp/blob/e56515f75123137042e109fb19ce5246b26653ae/silnlp/common/compare_translations.py#L34)):*
> ```Python
> 
> 
> def compare_translations(file_a: Path, file_b: Path, scorers: Set[str]) -> Dict[str, float]:
> ```

We want to use Machine to extract text segments from the Paratext projects and align them correctly.

 ``` py
corpus_a = ParatextTextCorpus("project1")
corpus_b = ParatextTextCorpus("project2")
parallel_corpus = corpus_a.align_rows(corpus_b)
with parallel_corpus.get_rows() as rows:
    for row in rows:
        a_lines.append(row.source_text)
        b_lines.append(row.target_text)
```


<!-- Sent from Reviewable.io -->

2024-09-10 19:48 UTC, ddaspit reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/510)* status: all files reviewed, 4 unresolved discussions (waiting on @mshannon-sil and @TaperChipmunk32)

___
*[`silnlp/common/compare_translations.py` line 14 at r2](https://reviewable.io/reviews/sillsdev/silnlp/510#-O6STNJI9zYUSVGH6w6v:-O6STNJI9zYUSVGH6w6w:b771vlw) ([raw file](https://github.com/sillsdev/silnlp/blob/f7f211b6849406adc5ca0b262758bf18491cc682/silnlp/common/compare_translations.py#L14)):*
> ```Python
>     parser = argparse.ArgumentParser(description="Compare translations")
>     parser.add_argument(
>         "--dir-paths", nargs=2, type=Path, required=True, help="Paths to the Paratext project directories"
> ```

I would class this `--project-paths`, or even just `--projects`.
___
*[`silnlp/common/compare_translations.py` line 17 at r2](https://reviewable.io/reviews/sillsdev/silnlp/510#-O6STLlvAlxhFUpFNZoa:-O6STLlvAlxhFUpFNZob:b-5z5uix) ([raw file](https://github.com/sillsdev/silnlp/blob/f7f211b6849406adc5ca0b262758bf18491cc682/silnlp/common/compare_translations.py#L17)):*
> ```Python
>     )
>     parser.add_argument(
>         "--output-path", type=Path, required=True, help="Path to the directory to save the comparison scores"
> ```

I would make this optional.
___
*[`silnlp/common/compare_translations.py` line 29 at r2](https://reviewable.io/reviews/sillsdev/silnlp/510#-O6SSyvv-Hg2yOpnZAPX:-O6SSyvv-Hg2yOpnZAPY:b-i1xys6) ([raw file](https://github.com/sillsdev/silnlp/blob/f7f211b6849406adc5ca0b262758bf18491cc682/silnlp/common/compare_translations.py#L29)):*
> ```Python
>     scores = compare_translations(args.dir_paths[0], args.dir_paths[1], args.scorers)
> 
>     with open(f"{args.output_path}/comparison_scores.txt", "w") as f:
> ```

I think it is good to have the option to save the scores to a file, but I would also print them to stdout.
___
*[`silnlp/common/compare_translations.py` line 32 at r2](https://reviewable.io/reviews/sillsdev/silnlp/510#-O6STBanCz_pkD6qhqsw:-O6STBanCz_pkD6qhqsx:b-60hyqd) ([raw file](https://github.com/sillsdev/silnlp/blob/f7f211b6849406adc5ca0b262758bf18491cc682/silnlp/common/compare_translations.py#L32)):*
> ```Python
>         f.write(f"Comparison of Translations in Paratext Projects: {args.dir_paths[0]} and {args.dir_paths[1]}\n")
>         for key, value in scores.items():
>             f.write(f"{key}: {value}\n")
> ```

I would make this comma or tab separated, so it can be pulled into a spreadsheet easily.


<!-- Sent from Reviewable.io -->

2024-09-10 21:46 UTC, mshannon-sil reviewed
@ddaspit  Just to confirm, should the compare_translations.py script go in silnlp/common? That's what I thought initially, but I'm seeing the `diff_predictions.py` script in silnlp/nmt, which has a pretty similar purpose but for test output instead of translation output, so I could maybe see this script going there.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/510#-:-O6Ssmrm3tK1FDwDsJDW:bnydstb)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ddaspit and @TaperChipmunk32)



<!-- Sent from Reviewable.io -->

2024-09-11 16:54 UTC, ddaspit approved these changes
Yes, `silnlp/common` is the right place for this script.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/510#-:-O6X-P9hAqv5BYLmB1Us:bywn7pi)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TaperChipmunk32)



<!-- Sent from Reviewable.io -->

2024-09-11 16:57 UTC, merged